
### Basic test for server
GET http://localhost:5000/api/test
###
@baseUrl = http://localhost:5000
@username = "enver"
@updatedusername = "enver updated"
@password = "1234"
@email = "enver@enver.com"


###Register a new user
POST {{baseUrl}}/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": {{username}},
    "email": {{email}},
    "password": {{password}}
}


###login
# @name Login
POST {{baseUrl}}/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": {{username}},
    "password": {{password}}
}

###Update User info
PUT  {{baseUrl}}/api/users/{{Login.response.body._id}} HTTP/1.1
Authorization: token Baerer  {{Login.response.body.accessToken}} 
content-type: application/json

{
    "username": {{updatedusername}}
}

###Update User info
PUT  {{baseUrl}}/api/users/{{Login.response.body._id}} HTTP/1.1
Authorization:  token Baerer {{Login.response.body.accessToken}} 
content-type: application/json

{
    "username": {{username}}
}
